In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

import re
import sys
import os

sys.path.append("/home/kalmar/Mathematics/Research/MPI Tuebingen/Dionysus-python3/build/bindings/python")
import dionysus

%reload_ext autoreload
%autoreload 2

from TDA import *
tsp

In [2]:
os.chdir("./test/pair0002")

In [3]:
p = CauseEffectPair("knn")

pair0002 knn scores stability done


In [4]:
A = p.out.geometric_complex.filtered_complex(0)

In [5]:
def f(i):
    print(A[i])
    print(p.out.geometric_complex.real_coords([x for x in A[i].vertices]))
    print(p.out.geometric_complex.sweep_function(A[i],0,inverse=False))
    

In [6]:
f(0), f(1), f(2), f(1000)

<70>
[[-1.13028707  0.09038328]]
0.0
<41>
[[-1.125795   -0.37983156]]
0.00449206216151
<301>
[[-1.125795    0.02975809]]
0.00449206216151
<82, 200>
[[ 1.03039483  0.86668135]
 [ 1.18312495  0.9248421 ]]
2.16068189969


(None, None, None, None)

In [7]:
1.18312495+1.13028707

2.3134120200000003

In [10]:
i = 1000
projection = p.out.geometric_complex.sweep_function
projection(A[1000],0,inverse=False)

2.1606818996870123

In [35]:
%timeit projection(A[1000],0,inverse=False)

The slowest run took 1248.59 times longer than the fastest. This could mean that an intermediate result is being cached 
10000 loops, best of 3: 26.4 µs per loop


[autoreload of TDA failed: Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/IPython/extensions/autoreload.py", line 247, in check
    superreload(m, reload, self.old_objects)
AttributeError: 'NoneType' object has no attribute 'name'
]


In [13]:
def proj(simplex, axis, inverse):
    x = simplex.vertices
        if simplex.dimension() == 0:
            vert = [next(x)]
        elif simplex.dimension() == 1:
            vert = [next(x), next(x)]
        else:
            pass

    simplex_real_coordinates = p.out.geometric_complex.real_coords(vertices=vert)
    print(simplex_real_coordinates)
    simplex_projection = simplex_real_coordinates[:, axis]
    print(simplex_projection)
    if not inverse:
        return max(simplex_projection) - (-1.13028707)
    if inverse:
        return self.maximums[axis] - min(simplex_projection)

In [14]:
proj(A[1000],0,inverse=False)

[82, 82]
[[ 1.03039483  0.86668135]
 [ 1.03039483  0.86668135]]
[ 1.03039483  1.03039483]


2.1606819036852007

In [26]:
x=A[1000].vertices
print(A[1000])
[v for v in x]

<82, 200>


[82, 200]

In [34]:
x=A[1000].vertices
print(next(A[1000].vertices),next(A[1000].vertices))

82 82


In [ ]:
simplex_projection = p.out.geometric_complex.real_coords([x for x in A[1000].vertices])

In [ ]:
print(simplex_projection)
print(simplex_projection[:,0])
print(max(simplex_projection[:,0]))


In [ ]:
%autoreload 2
from Scores_plotter import PairTopologyPlotter

In [ ]:
os.chdir("/home/kalmar/Mathematics/Research/MPI Tuebingen/TDA-Cause-Effect-Pairs")
p = PairTopologyPlotter('knn')

In [ ]:
p.plot_scores()

In [ ]:
plt.figure(figsize=(15,15))
p.plot_all_diagrams(40)

In [ ]:
p.diagrams[15]

In [ ]:
p.extrema[15]

In [ ]:
"inv" in "x_inv_fil"

In [ ]:
x = np.array([1,2,3,4]).reshape(2,2)

In [ ]:
x

In [ ]:
x - [2,2]